### PR TITLE
 Use the blowfish crate instead of rust-crypto

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Keats** [comment]
Super nice, thanks!

**Comment by Eijebong** [comment]
Forgot to release it :p

**Comment by Keats** [comment]
I didn't! Check #13 that I want to get in before releasing 0.2

**Comment by Eijebong** [comment]
Oh :+1:

**Comment by Keats** [comment]
It's published now

**Comment by Eijebong** [comment]
Thanks a lot :heart:

**Pull request merged**
