### PR TITLE
Fixed CI on 1.57.0

### PR DESCRIPTION
**Pull request by alex**
Some packages have semver compatible versions with higher MSRVs

### CODE REVIEW

**Comment by Keats** [comment]
We can probably raise the MSRV instead. Do you know what it is?

**Comment by alex** [comment]
It'd be 1.60

**Comment by Keats** [comment]
That's fine to bump. Enforcing MSRV is a losing battle anyway.

**Comment by alex** [comment]
Ok, i'll do it in the other PR then.

**Pull request closed without merging**
