### PR TITLE
Upgrade base64 to 0.22

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Failures are not connected to this PR, I don't believe.

**Review by Keats — APPROVED** [review]

**Comment by Keats** [comment]
That's fine, just need to update MSRV it seems

**Comment by alex** [comment]
https://github.com/Keats/rust-bcrypt/pull/83 fixes CI for the MSRV, when that merges I can rebase this.

**Comment by alex** [comment]
Ok, this should be ready to go.

**Pull request merged**
